name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v3 
      # Use the checkout package to reference files from the repo
      - name: Hello
        run: echo "Hello world"
      - name: Run Python Script
        run: |
          pip install -r requirements.txt
          python ci.py
      
